<?php
/** Approved Services page copy. @package VenixConcierge */
if ( ! defined( 'ABSPATH' ) ) { exit; }
function venix_concierge_services_content() {
	$copy = static function ( $english, $polish ) { return venix_concierge_language_copy( $english, $polish ); };
	return array(
		'hero' => array( 'eyebrow' => $copy( 'What we offer', 'Co oferujemy' ), 'title' => $copy( 'Every detail, considered in full', 'Każdy szczegół, dokładnie przemyślany' ) ),
		'anchors' => array( 'chauffeur' => $copy( 'Chauffeur', 'Szofer' ), 'airport' => $copy( 'Airport', 'Lotnisko' ), 'events' => $copy( 'Events', 'Wydarzenia' ), 'delegations' => $copy( 'Delegations', 'Delegacje' ), 'protection' => $copy( 'Protection', 'Ochrona' ), 'flights' => $copy( 'Private Flights', 'Loty prywatne' ), 'embassy' => $copy( 'Embassy', 'Ambasady' ), 'concierge' => 'Concierge', 'weddings' => $copy( 'Weddings', 'Śluby' ) ),
		'main_badge' => $copy( 'Main service', 'Usługa główna' ),
		'main' => array(
			array( 'id'=>'chauffeur','title'=>$copy('Chauffeur-driven transfers & private hire','Transfery z szoferem i wynajem prywatny'),'copy'=>$copy('A professional chauffeur and premium vehicle, arranged entirely around your itinerary. Whether you need a driver for a single appointment or a full day of engagements, the service is shaped to your schedule — not ours.','Profesjonalny szofer i pojazd klasy premium, zorganizowane w całości wokół Państwa planu. Niezależnie czy potrzebują Państwo kierowcy na jedno spotkanie, czy na cały dzień — usługa dostosowana jest do Państwa harmonogramu, nie naszego.'),'benefits'=>array($copy('Professional, experienced chauffeur','Profesjonalny, doświadczony szofer'),$copy('Premium Mercedes-Benz vehicle matched to requirements','Pojazd Mercedes-Benz klasy premium dobrany do wymagań'),$copy('Flexible pickup and destination, including multiple stops','Elastyczne miejsce odbioru i celu, w tym wiele przystanków'),$copy('Hourly, full-day and multi-day hire options','Wynajem na godziny, cały dzień i wiele dni'),$copy('Private and discreet at every stage','Prywatny i dyskretny na każdym etapie')),'audience'=>$copy('For: Private clients · Executives · Companies','Dla: Klientów prywatnych · Kadry zarządzającej · Firm'),'cta'=>$copy('Request a private transfer','Zamów transfer prywatny'),'alt'=>'Photography placeholder: a Venix Concierge chauffeur opening a Mercedes-Benz S-Class at a Warsaw business address.','surface'=>'warm','text_first'=>true ),
			array( 'id'=>'airport','title'=>$copy('Airport transfers','Transfery lotniskowe'),'copy'=>$copy("Professional arrivals and departures at Warsaw's airports. The vehicle is matched to the number of passengers and luggage. Multi-vehicle coordination is available for larger groups. Arrivals and departures are managed with care and clear communication.",'Profesjonalne przyloty i wyloty na warszawskich lotniskach. Pojazd dobierany jest do liczby pasażerów i bagażu. Dostępna koordynacja wielu pojazdów dla większych grup. Przyloty i wyloty są obsługiwane z troską i przejrzystą komunikacją.'),'benefits'=>array($copy('Vehicle matched to passenger count and luggage','Pojazd dobrany do liczby pasażerów i bagażu'),$copy('Arrivals and departures at Warsaw Chopin and other airports','Przyloty i wyloty na Okęciu i innych lotniskach'),$copy('Multi-vehicle coordination for groups','Koordynacja wielu pojazdów dla grup'),$copy('Clear communication from booking to arrival','Przejrzysta komunikacja od rezerwacji do przyjazdu'),$copy('Hotel, venue and onward connection transfers','Transfery do hotelu, obiektu i dalej')),'notice'=>$copy('Please note: flight tracking, free waiting time and terminal access are subject to confirmation. Share your flight details when making your request.','Uwaga: śledzenie lotów, bezpłatny czas oczekiwania i dostęp do terminala podlegają potwierdzeniu. Prosimy podać dane lotu przy składaniu zamówienia.'),'cta'=>$copy('Arrange an airport transfer','Umów transfer lotniskowy'),'alt'=>'Photography placeholder: a chauffeur waiting in a Warsaw airport arrivals hall with a name card.','surface'=>'neutral','media_first'=>true ),
			array( 'id'=>'events','title'=>$copy('Business & private events','Wydarzenia biznesowe i prywatne'),'copy'=>$copy('Transportation coordination for conferences, corporate dinners, exhibitions, galas and private celebrations. Multiple vehicles, coordinated schedules and a single point of contact — so the movement of your guests is handled as smoothly as the event itself.','Koordynacja transportu na konferencje, kolacje korporacyjne, wystawy, gale i uroczystości prywatne. Wiele pojazdów, skoordynowane harmonogramy i jeden punkt kontaktu — tak, aby przemieszczanie się gości przebiegało tak sprawnie jak samo wydarzenie.'),'benefits'=>array($copy('Multi-vehicle fleet coordination','Koordynacja floty wielu pojazdów'),$copy('Hotel-to-venue and return transfers','Transfery hotel–obiekt i powrotne'),$copy('Guest pickup schedules and manifests','Harmonogramy i listy odbioru gości'),$copy('Driver dispatch and on-site coordination','Dyspozycja kierowców i koordynacja na miejscu'),$copy('Airport arrivals for travelling guests','Przyloty lotniskowe dla gości z odległych miejsc'),$copy('Single point of contact for the organiser','Jeden punkt kontaktu dla organizatora')),'cta'=>$copy('Plan event transportation','Zaplanuj transport na wydarzenie'),'alt'=>'Photography placeholder: several Venix Concierge vehicles coordinated at a Warsaw conference centre entrance at dusk.','surface'=>'warm','text_first'=>true,'grid_benefits'=>true ),
			array( 'id'=>'delegations','title'=>$copy('Delegations & diplomatic transfers','Delegacje i transfery dyplomatyczne'),'copy'=>$copy('Discreet, punctual transportation for embassies, diplomatic delegations, government representatives and official guests visiting Warsaw. Arrangements are coordinated with your appointed team member, with full confidentiality at every stage.','Dyskretny, punktualny transport dla ambasad, delegacji dyplomatycznych, przedstawicieli rządowych i gości oficjalnych odwiedzających Warszawę. Ustalenia koordynowane są z wyznaczonym członkiem zespołu, przy zachowaniu pełnej poufności na każdym etapie.'),'benefits'=>array($copy('Full confidentiality at every stage','Pełna poufność na każdym etapie'),$copy('Multi-vehicle coordination for larger delegations','Koordynacja wielu pojazdów dla większych delegacji'),$copy('Airport, hotel, embassy and venue transfers','Transfery lotniskowe, hotelowe, ambasadowe i do obiektów'),$copy('Coordinated with your appointed team member','Koordynowane z wyznaczonym członkiem Państwa zespołu'),$copy('Professional vehicle presentation throughout','Profesjonalna prezentacja pojazdu przez cały czas')),'notice'=>$copy('Note: We do not claim diplomatic accreditation, police escort, special road privileges or government authorization.','Uwaga: Nie posiadamy akredytacji dyplomatycznej, eskorty policji, specjalnych uprawnień drogowych ani upoważnienia rządowego.'),'cta'=>$copy('Discuss a delegation requirement','Omów potrzeby delegacji'),'alt'=>'Photography placeholder: a black Mercedes-Benz S-Class arriving at an official Warsaw building entrance.','surface'=>'neutral','media_first'=>true,'last'=>true ),
		),
		'additional' => array( 'title'=>$copy('Other services','Inne usługi'),'copy'=>$copy('A selection of specialist services, coordinated through appropriate, authorised partners and subject to assessment, availability and applicable regulations.','Wybrane usługi specjalistyczne koordynowane przez odpowiednich, autoryzowanych partnerów, podlegające ocenie, dostępności i obowiązującym przepisom.'),'notice'=>$copy('For each additional service, we will clarify scope, availability and partner arrangements as part of your inquiry response. We do not make guarantees regarding service availability.','Dla każdej usługi dodatkowej wyjaśnimy zakres, dostępność i ustalenia z partnerami w odpowiedzi na zapytanie. Nie składamy gwarancji dotyczących dostępności usług.'),'badge'=>$copy('Additional service','Usługa dodatkowa'),'compact_badge'=>$copy('Additional','Dodatkowa') ),
		'protection' => array( 'title'=>$copy('Private protection','Ochrona osobista'),'copy'=>$copy('Coordination of professional security arrangements through authorised and appropriately licensed providers. This may include close protection, secure transport coordination and risk-aware planning for events or travel.','Koordynacja profesjonalnych ustaleń bezpieczeństwa przez autoryzowanych i odpowiednio licencjonowanych dostawców. Może obejmować ochronę osobistą, koordynację bezpiecznego transportu i planowanie z uwzględnieniem ryzyka.'),'notice'=>$copy('Subject to assessment, provider availability, licensing requirements and applicable regulations.','Podlega ocenie, dostępności dostawcy, wymogom licencyjnym i obowiązującym przepisom.'),'cta'=>$copy('Discuss a protection requirement','Omów potrzebę ochrony') ),
		'flights' => array( 'title'=>$copy('Private flights','Loty prywatne'),'copy'=>$copy('Assistance with private charter inquiries, ground-to-air coordination and chauffeur transfers to and from airports for private aviation. We do not operate aircraft or hold air-carrier status — we coordinate the ground experience around your flight.','Wsparcie przy zapytaniach czarterowych, koordynacja transportu naziemno-lotniczego i transfery szoferskie na lotniska dla lotnictwa prywatnego. Nie obsługujemy samolotów ani nie posiadamy statusu przewoźnika lotniczego — koordynujemy doświadczenie naziemne wokół lotu.'),'cta'=>$copy('Request private aviation assistance','Zapytaj o wsparcie lotnicze') ),
		'compact' => array(
			array('id'=>'embassy','title'=>$copy('Embassy services','Obsługa ambasad'),'copy'=>$copy('Transportation and scheduling support for official visitors, embassy guests and diplomatic delegations — airport arrivals, hotel connections and venue transfers handled with discretion.','Transport i wsparcie logistyczne dla gości oficjalnych, gości ambasad i delegacji dyplomatycznych — przyloty lotniskowe, połączenia hotelowe i transfery do obiektów obsługiwane z dyskrecją.'),'cta'=>$copy('Discuss requirements','Omów wymagania'),'surface'=>'warm'),
			array('id'=>'concierge','title'=>$copy('Concierge services','Usługi concierge'),'copy'=>$copy('Personalised assistance surrounding your visit — restaurant reservations, hotel coordination, itinerary support, shopping appointments and other practical arrangements that enhance your time in Warsaw.','Spersonalizowana pomoc wokół Państwa wizyty — rezerwacje restauracji, koordynacja hotelu, wsparcie przy planowaniu pobytu, terminy zakupów i inne praktyczne ustalenia zwiększające komfort pobytu w Warszawie.'),'cta'=>$copy('Request concierge assistance','Zamów usługi concierge'),'surface'=>'neutral'),
			array('id'=>'weddings','title'=>$copy('Weddings','Śluby i wesela'),'copy'=>$copy('Elegant, precisely timed transportation for couples, families and guests. Multiple vehicles, coordinated pickups, hotel-to-venue transfers and evening returns — all managed with care and presentation.','Elegancki, punktualny transport dla pary młodej, rodzin i gości. Wiele pojazdów, skoordynowane odbiory, transfery hotel-obiekt i powroty wieczorne — wszystko z troską i należytą prezentacją.'),'cta'=>$copy('Plan wedding transportation','Zaplanuj transport ślubny'),'surface'=>'warm'),
		),
		'cta' => array('title'=>$copy('Not sure which service you need?','Nie wiedzą Państwo, która usługa jest właściwa?'),'copy'=>$copy('Tell us about your journey, occasion or requirements. We will recommend the most appropriate arrangement and follow up with a clear proposal.','Prosimy opisać podróż, okazję lub wymagania. Zarekomendujemy najbardziej odpowiednie rozwiązanie i odpowiemy z jasną propozycją.'),'button'=>$copy('Discuss your requirements','Omów swoje potrzeby')),
		'footer' => array(
			'brand_copy'          => $copy( 'Chauffeur services, executive transportation and luxury concierge in Warsaw.', 'Usługi szoferskie, transport reprezentacyjny i concierge w Warszawie.' ),
			'navigation'          => $copy( 'Navigation', 'Nawigacja' ),
			'contact_heading'     => $copy( 'Contact', 'Kontakt' ),
			'location'            => $copy( 'Warsaw, Poland', 'Warszawa' ),
			'contact_placeholder' => '[Insert verified phone]',
		),
	);
}
