<?php
/** One shared four-column footer for every page: Brand, Navigation, Services, Contact. @package VenixConcierge */
$venix_concierge_footer_content  = venix_concierge_footer_content();
$venix_concierge_contact_items   = venix_concierge_get_footer_contact_items();
$venix_concierge_company_name    = venix_concierge_get_site_setting( 'company_name' );
$venix_concierge_copyright_name  = venix_concierge_get_site_setting( 'legal_name', get_bloginfo( 'name' ) );
?>
<footer class="site-footer"<?php echo '' !== $venix_concierge_company_name ? ' aria-label="' . esc_attr( $venix_concierge_company_name ) . '"' : ''; ?>><div class="container site-footer__inner">
	<div class="site-footer__brand"><strong>VENIX <small>CONCIERGE</small></strong><p><?php echo esc_html( $venix_concierge_footer_content['brand_copy'] ); ?></p><span><?php echo esc_html( $venix_concierge_footer_content['tagline'] ); ?></span></div>
	<div class="site-footer__column"><h2><?php echo esc_html( $venix_concierge_footer_content['navigation'] ); ?></h2><?php if ( has_nav_menu( 'footer' ) ) { wp_nav_menu( array( 'theme_location' => 'footer', 'container' => 'nav', 'container_aria_label' => $venix_concierge_footer_content['navigation'], 'fallback_cb' => false ) ); } ?></div>
	<div class="site-footer__column"><h2><?php echo esc_html( $venix_concierge_footer_content['services_heading'] ); ?></h2><nav aria-label="<?php echo esc_attr( $venix_concierge_footer_content['services_heading'] ); ?>"><ul><?php foreach ( $venix_concierge_footer_content['services'] as $venix_concierge_service ) : ?><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', $venix_concierge_service[0] ) ); ?>"><?php echo esc_html( $venix_concierge_service[1] ); ?></a></li><?php endforeach; ?></ul></nav></div>
	<div class="site-footer__column site-footer__contact"><h2><?php echo esc_html( $venix_concierge_footer_content['contact_heading'] ); ?></h2><?php if ( $venix_concierge_contact_items ) : ?><ul><?php foreach ( $venix_concierge_contact_items as $venix_concierge_item ) : ?><li class="site-footer__contact-<?php echo esc_attr( $venix_concierge_item['type'] ); ?>"><?php if ( '' !== $venix_concierge_item['url'] ) : ?><a href="<?php echo esc_url( $venix_concierge_item['url'] ); ?>"><?php echo esc_html( $venix_concierge_item['text'] ); ?></a><?php else : ?><?php echo esc_html( $venix_concierge_item['text'] ); ?><?php endif; ?></li><?php endforeach; ?></ul><?php endif; ?></div>
	<div class="site-footer__bottom"><p>&copy; <?php echo esc_html( wp_date( 'Y' ) ); ?> <?php echo esc_html( $venix_concierge_copyright_name ); ?></p><?php if ( has_nav_menu( 'legal' ) ) { wp_nav_menu( array( 'theme_location' => 'legal', 'container' => 'nav', 'container_aria_label' => __( 'Legal navigation', 'venix-concierge' ), 'fallback_cb' => false ) ); } ?></div>
</div></footer>
