<?php
/** Home composition. Editorial copy and media are migration defaults pending client entry. @package VenixConcierge */
$venix_concierge_home_content = venix_concierge_home_content();
$services = $venix_concierge_home_content['cards'];
$promise_items = $venix_concierge_home_content['promise']['items'];
$pillars = $venix_concierge_home_content['pillars'];
$event_points = $venix_concierge_home_content['events']['points'];
$steps = $venix_concierge_home_content['process'];
$extras = $venix_concierge_home_content['extras'];
$audiences = $venix_concierge_home_content['audience']['items'];
?>
<main id="primary" class="site-main venix-home">
	<section class="home-hero"><div class="home-hero__media" aria-hidden="true"></div><div class="container home-hero__content"><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['hero']['eyebrow'] ); ?></p><h1><?php echo esc_html( $venix_concierge_home_content['hero']['title'] ); ?></h1><p class="home-hero__lead"><?php echo esc_html( $venix_concierge_home_content['hero']['lead'] ); ?></p><p class="home-actions"><a class="venix-button venix-button--primary" href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['hero']['primary'] ); ?></a><a class="venix-button venix-button--ghost-inverse" href="#fleet"><?php echo esc_html( $venix_concierge_home_content['hero']['secondary'] ); ?></a></p><small><?php echo esc_html( $venix_concierge_home_content['hero']['caption'] ); ?></small></div><span class="home-hero__scroll" aria-hidden="true">SCROLL</span></section>
	<section id="about" class="section home-split" data-venix-reveal><div class="container home-split__grid"><div><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['intro']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['intro']['title'] ); ?></h2><p><?php echo esc_html( $venix_concierge_home_content['intro']['copy'] ); ?></p><p><?php echo esc_html( $venix_concierge_home_content['intro']['closing'] ); ?></p><a class="venix-button venix-button--text" href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['intro']['cta'] ); ?></a></div><div class="venix-media venix-media--portrait" role="img" aria-label="<?php esc_attr_e( 'Photography placeholder: chauffeur beside a premium vehicle in Warsaw.', 'venix-concierge' ); ?>"></div></div></section>
	<section id="services" class="section home-services" data-venix-reveal><div class="container"><header class="home-heading"><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['services']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['services']['title'] ); ?></h2></header><div class="home-services__grid"><?php foreach ( $services as $service ) : ?><article class="home-service"><div class="venix-media venix-media--landscape" aria-hidden="true"></div><div><span></span><h3><?php echo esc_html( $service[0] ); ?></h3><p><?php echo esc_html( $service[1] ); ?></p><small><?php echo esc_html( $service[2] ); ?></small><a href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['services']['link'] ); ?> →</a></div></article><?php endforeach; ?></div></div></section>
	<section class="home-quote" data-venix-reveal><blockquote>“<?php echo esc_html( $venix_concierge_home_content['quote'] ); ?>”</blockquote></section>
	<section class="section home-promise" data-venix-reveal><div class="container home-split__grid"><div><h2><?php echo esc_html( $venix_concierge_home_content['promise']['title'] ); ?></h2><p><?php echo esc_html( $venix_concierge_home_content['promise']['copy'] ); ?></p><div class="home-detail-grid"><?php foreach ( $promise_items as $item ) : ?><div><h3><?php echo esc_html( $item[0] ); ?></h3><p><?php echo esc_html( $item[1] ); ?></p></div><?php endforeach; ?></div></div><div class="venix-media venix-media--portrait" aria-label="<?php esc_attr_e( 'Photography placeholder: chauffeur adjusting cufflinks.', 'venix-concierge' ); ?>" role="img"></div></div></section>
	<section id="fleet" class="section home-fleet" data-venix-reveal><div class="container"><header class="home-fleet__header"><div><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['fleet']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['fleet']['title'] ); ?></h2><p><?php echo esc_html( $venix_concierge_home_content['fleet']['copy'] ); ?></p></div><small><?php echo esc_html( $venix_concierge_home_content['fleet']['note'] ); ?></small></header><article class="home-fleet__featured"><div class="venix-media venix-media--landscape" aria-hidden="true"></div><div><span class="home-badge"><?php echo esc_html( $venix_concierge_home_content['fleet']['featured'][0] ); ?></span><small><?php echo esc_html( $venix_concierge_home_content['fleet']['featured'][1] ); ?></small><h3><?php echo esc_html( $venix_concierge_home_content['fleet']['featured'][2] ); ?></h3><p><?php echo esc_html( $venix_concierge_home_content['fleet']['featured'][3] ); ?></p><em><?php echo esc_html( $venix_concierge_home_content['fleet']['capacity_placeholder'] ); ?></em><a class="venix-button venix-button--primary" href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['fleet']['featured'][4] ); ?></a></div></article><div class="home-fleet__grid"><?php foreach ( $venix_concierge_home_content['fleet']['vehicles'] as $vehicle ) : ?><article><div class="venix-media venix-media--landscape" aria-hidden="true"></div><span class="home-badge"><?php echo esc_html( $vehicle[0] ); ?></span><h3><?php echo esc_html( $vehicle[1] ); ?></h3><p><?php echo esc_html( $vehicle[2] ); ?></p><em><?php echo esc_html( $venix_concierge_home_content['fleet']['capacity_placeholder'] ); ?></em><a href="#inquiry"><?php echo esc_html( $vehicle[3] ); ?> →</a></article><?php endforeach; ?></div><aside class="home-fleet__helper"><strong><?php echo esc_html( $venix_concierge_home_content['fleet']['helper_title'] ); ?></strong><span><?php echo esc_html( $venix_concierge_home_content['fleet']['helper_copy'] ); ?></span><a href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['fleet']['helper_cta'] ); ?> →</a></aside></div></section>
	<section id="why" class="section home-why" data-venix-reveal><div class="container"><header class="home-heading"><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['why']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['why']['title'] ); ?></h2></header><div class="home-pillars"><?php foreach ( $pillars as $index => $pillar ) : ?><article><strong>0<?php echo esc_html( (string) ( $index + 1 ) ); ?></strong><h3><?php echo esc_html( $pillar[0] ); ?></h3><p><?php echo esc_html( $pillar[1] ); ?></p></article><?php endforeach; ?></div></div></section>
	<section id="events" class="section home-events" data-venix-reveal><div class="container home-split__grid"><div><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['events']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['events']['title'] ); ?></h2><p><?php echo esc_html( $venix_concierge_home_content['events']['copy'] ); ?></p><ul><?php foreach ( $event_points as $point ) : ?><li><?php echo esc_html( $point ); ?></li><?php endforeach; ?></ul><a class="venix-button venix-button--ghost-inverse" href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['events']['cta'] ); ?></a></div><div class="venix-media venix-media--portrait" aria-hidden="true"></div></div></section>
	<section id="process" class="section home-process" data-venix-reveal><div class="container"><header class="home-heading"><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['process_heading']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['process_heading']['title'] ); ?></h2></header><ol><?php foreach ( $steps as $step ) : ?><li><strong><?php echo esc_html( $step[0] ); ?></strong><h3><?php echo esc_html( $step[1] ); ?></h3><p><?php echo esc_html( $step[2] ); ?></p></li><?php endforeach; ?></ol></div></section>
	<section id="additional" class="section home-additional" data-venix-reveal><div class="container"><header class="home-heading"><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['extras_heading']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['extras_heading']['title'] ); ?></h2></header><div class="home-extras"><?php foreach ( $extras as $extra ) : ?><article><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"></circle><path d="M12 8v8M8 12h8"></path></svg><h3><?php echo esc_html( $extra[0] ); ?></h3><p><?php echo esc_html( $extra[1] ); ?></p><a href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['extras_heading']['link'] ); ?> →</a></article><?php endforeach; ?></div><p class="home-disclaimer"><?php echo esc_html( $venix_concierge_home_content['extras_heading']['disclaimer'] ); ?></p></div></section>
	<section class="section home-audience" data-venix-reveal><div class="container"><header><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['audience']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['audience']['title'] ); ?></h2></header><div class="home-audience-grid"><?php foreach ( $audiences as $audience ) : ?><article><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="8" r="3"></circle><path d="M5 21v-2a7 7 0 0 1 14 0v2"></path></svg><h3><?php echo esc_html( $audience[0] ); ?></h3><p><?php echo esc_html( $audience[1] ); ?></p></article><?php endforeach; ?></div><p><a class="venix-button venix-button--ghost-inverse" href="#inquiry"><?php echo esc_html( $venix_concierge_home_content['audience']['cta'] ); ?></a></p></div></section>
	<section class="section home-testimonial" data-venix-reveal><div class="container"><b aria-hidden="true">“</b><p><?php echo esc_html( $venix_concierge_home_content['testimonial']['quote'] ); ?></p><small><?php echo esc_html( $venix_concierge_home_content['testimonial']['attribution'] ); ?></small></div></section>
	<section id="inquiry" class="section home-inquiry" data-venix-reveal><div class="container home-split__grid"><div><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_home_content['form']['eyebrow'] ); ?></p><h2><?php echo esc_html( $venix_concierge_home_content['form']['title'] ); ?></h2><p><?php echo esc_html( $venix_concierge_home_content['form']['lead'] ); ?></p><p><?php echo esc_html( $venix_concierge_home_content['form']['contact_note'] ); ?></p></div><form class="home-form" action="#inquiry" method="post" aria-describedby="home-form-note"><div class="home-form__grid"><?php foreach ( $venix_concierge_home_content['form']['fields'] as $field ) : ?><p class="venix-field"><label class="venix-field__label" for="<?php echo esc_attr( $field[0] ); ?>"><?php echo esc_html( $field[1] ); ?><?php echo $field[4] ? ' *' : ''; ?></label><input class="venix-field__control" id="<?php echo esc_attr( $field[0] ); ?>" name="<?php echo esc_attr( $field[3] ); ?>" type="<?php echo esc_attr( $field[2] ); ?>"<?php echo $field[4] ? ' required aria-invalid="false"' : ''; ?><?php echo $field[5] ? ' autocomplete="' . esc_attr( $field[5] ) . '"' : ''; ?>></p><?php endforeach; ?><p class="venix-field"><label class="venix-field__label" for="home-service"><?php echo esc_html( $venix_concierge_home_content['form']['service_label'] ); ?> *</label><span class="venix-field__select-wrap"><select class="venix-field__control venix-field__control--select" id="home-service" required aria-invalid="false"><?php foreach ( $venix_concierge_home_content['form']['service'] as $venix_concierge_service_option ) : ?><option><?php echo esc_html( $venix_concierge_service_option ); ?></option><?php endforeach; ?></select></span></p></div><p class="venix-field"><label class="venix-field__label" for="home-message"><?php echo esc_html( $venix_concierge_home_content['form']['message_label'] ); ?></label><textarea class="venix-field__control venix-field__control--textarea" id="home-message" name="message"></textarea></p><p><label><input type="checkbox" required> <?php echo esc_html( $venix_concierge_home_content['form']['consent'] ); ?></label></p><p id="home-form-note" class="venix-field__hint"><?php echo esc_html( $venix_concierge_home_content['form']['status'] ); ?></p><button class="venix-button venix-button--primary" type="submit" disabled aria-disabled="true"><?php echo esc_html( $venix_concierge_home_content['form']['submit_placeholder'] ); ?></button></form></div></section>
</main>
