<?php
/**
 * Services page composition.
 *
 * @package VenixConcierge
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$venix_concierge_contact_url = venix_concierge_page_url( 'contact' );
$venix_concierge_main_services = array(
	array( 'id' => 'chauffeur', 'title' => 'Chauffeur-driven transfers & private hire', 'copy' => 'A professional chauffeur and premium vehicle, arranged entirely around your itinerary. Whether you need a driver for a single appointment or a full day of engagements, the service is shaped to your schedule — not ours.', 'benefits' => array( 'Professional, experienced chauffeur', 'Premium Mercedes-Benz vehicle matched to requirements', 'Flexible pickup and destination, including multiple stops', 'Hourly, full-day and multi-day hire options', 'Private and discreet at every stage' ), 'audience' => 'For: Private clients · Executives · Companies', 'cta' => 'Request a private transfer', 'alt' => 'Photography placeholder: a Venix Concierge chauffeur opening a Mercedes-Benz S-Class at a Warsaw business address.', 'surface' => 'warm', 'text_first' => true ),
	array( 'id' => 'airport', 'title' => 'Airport transfers', 'copy' => "Professional arrivals and departures at Warsaw's airports. The vehicle is matched to the number of passengers and luggage. Multi-vehicle coordination is available for larger groups. Arrivals and departures are managed with care and clear communication.", 'benefits' => array( 'Vehicle matched to passenger count and luggage', 'Arrivals and departures at Warsaw Chopin and other airports', 'Multi-vehicle coordination for groups', 'Clear communication from booking to arrival', 'Hotel, venue and onward connection transfers' ), 'notice' => 'Please note: flight tracking, free waiting time and terminal access are subject to confirmation. Share your flight details when making your request.', 'cta' => 'Arrange an airport transfer', 'alt' => 'Photography placeholder: a chauffeur waiting in a Warsaw airport arrivals hall with a name card.', 'surface' => 'neutral', 'media_first' => true ),
	array( 'id' => 'events', 'title' => 'Business & private events', 'copy' => 'Transportation coordination for conferences, corporate dinners, exhibitions, galas and private celebrations. Multiple vehicles, coordinated schedules and a single point of contact — so the movement of your guests is handled as smoothly as the event itself.', 'benefits' => array( 'Multi-vehicle fleet coordination', 'Hotel-to-venue and return transfers', 'Guest pickup schedules and manifests', 'Driver dispatch and on-site coordination', 'Airport arrivals for travelling guests', 'Single point of contact for the organiser' ), 'cta' => 'Plan event transportation', 'alt' => 'Photography placeholder: several Venix Concierge vehicles coordinated at a Warsaw conference centre entrance at dusk.', 'surface' => 'warm', 'text_first' => true, 'grid_benefits' => true ),
	array( 'id' => 'delegations', 'title' => 'Delegations & diplomatic transfers', 'copy' => 'Discreet, punctual transportation for embassies, diplomatic delegations, government representatives and official guests visiting Warsaw. Arrangements are coordinated with your appointed team member, with full confidentiality at every stage.', 'benefits' => array( 'Full confidentiality at every stage', 'Multi-vehicle coordination for larger delegations', 'Airport, hotel, embassy and venue transfers', 'Coordinated with your appointed team member', 'Professional vehicle presentation throughout' ), 'notice' => 'Note: We do not claim diplomatic accreditation, police escort, special road privileges or government authorization.', 'cta' => 'Discuss a delegation requirement', 'alt' => 'Photography placeholder: a black Mercedes-Benz S-Class arriving at an official Warsaw building entrance.', 'surface' => 'neutral', 'media_first' => true, 'last' => true ),
);
$venix_concierge_compact_services = array(
	array( 'id' => 'embassy', 'title' => 'Embassy services', 'copy' => 'Transportation and scheduling support for official visitors, embassy guests and diplomatic delegations — airport arrivals, hotel connections and venue transfers handled with discretion.', 'cta' => 'Discuss requirements', 'surface' => 'warm' ),
	array( 'id' => 'concierge', 'title' => 'Concierge services', 'copy' => 'Personalised assistance surrounding your visit — restaurant reservations, hotel coordination, itinerary support, shopping appointments and other practical arrangements that enhance your time in Warsaw.', 'cta' => 'Request concierge assistance', 'surface' => 'neutral' ),
	array( 'id' => 'weddings', 'title' => 'Weddings', 'copy' => 'Elegant, precisely timed transportation for couples, families and guests. Multiple vehicles, coordinated pickups, hotel-to-venue transfers and evening returns — all managed with care and presentation.', 'cta' => 'Plan wedding transportation', 'surface' => 'warm' ),
);
?>
<main id="main-content" class="site-main venix-services">
	<section class="services-hero"><div class="services-hero__media" aria-hidden="true"></div><div class="container services-hero__content"><p class="venix-eyebrow">What we offer</p><h1>Every detail, considered in full</h1></div></section>
	<nav class="services-anchor-nav" aria-label="Service sections"><div class="container services-anchor-nav__inner"><?php foreach ( array( 'chauffeur' => 'Chauffeur', 'airport' => 'Airport', 'events' => 'Events', 'delegations' => 'Delegations', 'protection' => 'Protection', 'flights' => 'Private Flights', 'embassy' => 'Embassy', 'concierge' => 'Concierge', 'weddings' => 'Weddings' ) as $venix_concierge_anchor => $venix_concierge_label ) : ?><a href="#<?php echo esc_attr( $venix_concierge_anchor ); ?>"><?php echo esc_html( $venix_concierge_label ); ?></a><?php endforeach; ?></div></nav>
	<div class="services-main">
		<?php foreach ( $venix_concierge_main_services as $venix_concierge_service ) : ?>
		<section id="<?php echo esc_attr( $venix_concierge_service['id'] ); ?>" class="services-split services-split--<?php echo esc_attr( $venix_concierge_service['surface'] ); ?><?php echo ! empty( $venix_concierge_service['last'] ) ? ' services-split--last' : ''; ?>"><div class="container services-split__inner">
				<div class="services-split__copy<?php echo ! empty( $venix_concierge_service['text_first'] ) ? ' services-split__copy--first' : ''; ?>"><div class="services-split__badge"><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => 'Main service', 'tone' => 'solid' ) ); ?></div><h2><?php echo esc_html( $venix_concierge_service['title'] ); ?></h2><span class="services-rule" aria-hidden="true"></span><p><?php echo esc_html( $venix_concierge_service['copy'] ); ?></p><ul class="services-benefits<?php echo ! empty( $venix_concierge_service['grid_benefits'] ) ? ' services-benefits--grid' : ''; ?>"><?php foreach ( $venix_concierge_service['benefits'] as $venix_concierge_benefit ) : ?><li><?php echo esc_html( $venix_concierge_benefit ); ?></li><?php endforeach; ?></ul><?php if ( ! empty( $venix_concierge_service['audience'] ) ) : ?><p class="services-audience"><?php echo esc_html( $venix_concierge_service['audience'] ); ?></p><?php endif; ?><?php if ( ! empty( $venix_concierge_service['notice'] ) ) : ?><p class="services-notice"><?php echo esc_html( $venix_concierge_service['notice'] ); ?></p><?php endif; ?><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => $venix_concierge_service['cta'], 'url' => $venix_concierge_contact_url, 'variant' => 'primary' ) ); ?></div>
				<div class="services-media<?php echo ! empty( $venix_concierge_service['media_first'] ) ? ' services-media--first' : ''; ?>" role="img" aria-label="<?php echo esc_attr( $venix_concierge_service['alt'] ); ?>"></div>
			</div></section>
		<?php endforeach; ?>
	</div>
	<section id="additional" class="services-additional-intro"><div class="container services-additional-intro__inner"><div><h2>Other services</h2><p>A selection of specialist services, coordinated through appropriate, authorised partners and subject to assessment, availability and applicable regulations.</p></div><p>For each additional service, we will clarify scope, availability and partner arrangements as part of your inquiry response. We do not make guarantees regarding service availability.</p></div></section>
	<section id="protection" class="services-split services-split--warm services-split--additional"><div class="container services-split__inner"><div class="services-split__copy services-split__copy--first"><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => 'Additional service', 'tone' => 'brand' ) ); ?><h2>Private protection</h2><span class="services-rule" aria-hidden="true"></span><p>Coordination of professional security arrangements through authorised and appropriately licensed providers. This may include close protection, secure transport coordination and risk-aware planning for events or travel.</p><p class="services-disclaimer">Subject to assessment, provider availability, licensing requirements and applicable regulations.</p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => 'Discuss a protection requirement', 'url' => $venix_concierge_contact_url, 'variant' => 'text' ) ); ?></div><div class="services-media" role="img" aria-label="Photography placeholder: a discreet private protection coordination scenario."></div></div></section>
	<section id="flights" class="services-split services-split--neutral services-split--additional"><div class="container services-split__inner"><div class="services-media" role="img" aria-label="Photography placeholder: a private aviation terminal with a Mercedes-Benz S-Class nearby."></div><div class="services-split__copy"><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => 'Additional service', 'tone' => 'brand' ) ); ?><h2>Private flights</h2><span class="services-rule" aria-hidden="true"></span><p>Assistance with private charter inquiries, ground-to-air coordination and chauffeur transfers to and from airports for private aviation. We do not operate aircraft or hold air-carrier status — we coordinate the ground experience around your flight.</p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => 'Request private aviation assistance', 'url' => $venix_concierge_contact_url, 'variant' => 'text' ) ); ?></div></div></section>
	<section class="services-compact"><div class="container services-compact__grid"><?php foreach ( $venix_concierge_compact_services as $venix_concierge_service ) : ?><article id="<?php echo esc_attr( $venix_concierge_service['id'] ); ?>" class="services-compact__card services-compact__card--<?php echo esc_attr( $venix_concierge_service['surface'] ); ?>"><div class="services-compact__media" role="img" aria-label="Photography placeholder for <?php echo esc_attr( $venix_concierge_service['title'] ); ?>."></div><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => 'Additional', 'tone' => 'brand' ) ); ?><h2><?php echo esc_html( $venix_concierge_service['title'] ); ?></h2><span class="services-rule" aria-hidden="true"></span><p><?php echo esc_html( $venix_concierge_service['copy'] ); ?></p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => $venix_concierge_service['cta'], 'url' => $venix_concierge_contact_url, 'variant' => 'text', 'size' => 'sm' ) ); ?></article><?php endforeach; ?></div></section>
	<section class="services-cta"><div class="container services-cta__content"><h2>Not sure which service you need?</h2><p>Tell us about your journey, occasion or requirements. We will recommend the most appropriate arrangement and follow up with a clear proposal.</p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => 'Discuss your requirements', 'url' => $venix_concierge_contact_url, 'variant' => 'gold' ) ); ?></div></section>
</main>
