<?php
/**
 * Services page composition.
 *
 * @package VenixConcierge
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$venix_concierge_contact_url      = venix_concierge_page_url( 'contact' );
$venix_concierge_services_content = venix_concierge_services_content();
$venix_concierge_main_services    = $venix_concierge_services_content['main'];
$venix_concierge_compact_services = $venix_concierge_services_content['compact'];
?>
<main id="main-content" class="site-main venix-services">
	<section class="services-hero"><div class="services-hero__media" aria-hidden="true"></div><div class="container services-hero__content"><p class="venix-eyebrow"><?php echo esc_html( $venix_concierge_services_content['hero']['eyebrow'] ); ?></p><h1><?php echo esc_html( $venix_concierge_services_content['hero']['title'] ); ?></h1></div></section>
	<nav class="services-anchor-nav" aria-label="Service sections"><div class="container services-anchor-nav__inner"><?php foreach ( $venix_concierge_services_content['anchors'] as $venix_concierge_anchor => $venix_concierge_label ) : ?><a href="#<?php echo esc_attr( $venix_concierge_anchor ); ?>"><?php echo esc_html( $venix_concierge_label ); ?></a><?php endforeach; ?></div></nav>
	<div class="services-main">
		<?php foreach ( $venix_concierge_main_services as $venix_concierge_service ) : ?>
		<section id="<?php echo esc_attr( $venix_concierge_service['id'] ); ?>" class="services-split services-split--<?php echo esc_attr( $venix_concierge_service['surface'] ); ?><?php echo ! empty( $venix_concierge_service['last'] ) ? ' services-split--last' : ''; ?>"><div class="container services-split__inner">
			<div class="services-split__copy<?php echo ! empty( $venix_concierge_service['text_first'] ) ? ' services-split__copy--first' : ''; ?>"><div class="services-split__badge"><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => $venix_concierge_services_content['main_badge'], 'tone' => 'solid' ) ); ?></div><h2><?php echo esc_html( $venix_concierge_service['title'] ); ?></h2><span class="services-rule" aria-hidden="true"></span><p><?php echo esc_html( $venix_concierge_service['copy'] ); ?></p><ul class="services-benefits<?php echo ! empty( $venix_concierge_service['grid_benefits'] ) ? ' services-benefits--grid' : ''; ?>"><?php foreach ( $venix_concierge_service['benefits'] as $venix_concierge_benefit ) : ?><li><?php echo esc_html( $venix_concierge_benefit ); ?></li><?php endforeach; ?></ul><?php if ( ! empty( $venix_concierge_service['audience'] ) ) : ?><p class="services-audience"><?php echo esc_html( $venix_concierge_service['audience'] ); ?></p><?php endif; ?><?php if ( ! empty( $venix_concierge_service['notice'] ) ) : ?><p class="services-notice"><?php echo esc_html( $venix_concierge_service['notice'] ); ?></p><?php endif; ?><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => $venix_concierge_service['cta'], 'url' => $venix_concierge_contact_url, 'variant' => 'primary' ) ); ?></div>
			<div class="services-media<?php echo ! empty( $venix_concierge_service['media_first'] ) ? ' services-media--first' : ''; ?>" role="img" aria-label="<?php echo esc_attr( $venix_concierge_service['alt'] ); ?>"></div>
		</div></section>
		<?php endforeach; ?>
	</div>
	<section id="additional" class="services-additional-intro"><div class="container services-additional-intro__inner"><div><h2><?php echo esc_html( $venix_concierge_services_content['additional']['title'] ); ?></h2><p><?php echo esc_html( $venix_concierge_services_content['additional']['copy'] ); ?></p></div><p><?php echo esc_html( $venix_concierge_services_content['additional']['notice'] ); ?></p></div></section>
	<section id="protection" class="services-split services-split--warm services-split--additional"><div class="container services-split__inner"><div class="services-split__copy services-split__copy--first"><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => $venix_concierge_services_content['additional']['badge'], 'tone' => 'brand' ) ); ?><h2><?php echo esc_html( $venix_concierge_services_content['protection']['title'] ); ?></h2><span class="services-rule" aria-hidden="true"></span><p><?php echo esc_html( $venix_concierge_services_content['protection']['copy'] ); ?></p><p class="services-disclaimer"><?php echo esc_html( $venix_concierge_services_content['protection']['notice'] ); ?></p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => $venix_concierge_services_content['protection']['cta'], 'url' => $venix_concierge_contact_url, 'variant' => 'text' ) ); ?></div><div class="services-media" role="img" aria-label="Photography placeholder: a discreet private protection coordination scenario."></div></div></section>
	<section id="flights" class="services-split services-split--neutral services-split--additional"><div class="container services-split__inner"><div class="services-media" role="img" aria-label="Photography placeholder: a private aviation terminal with a Mercedes-Benz S-Class nearby."></div><div class="services-split__copy"><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => $venix_concierge_services_content['additional']['badge'], 'tone' => 'brand' ) ); ?><h2><?php echo esc_html( $venix_concierge_services_content['flights']['title'] ); ?></h2><span class="services-rule" aria-hidden="true"></span><p><?php echo esc_html( $venix_concierge_services_content['flights']['copy'] ); ?></p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => $venix_concierge_services_content['flights']['cta'], 'url' => $venix_concierge_contact_url, 'variant' => 'text' ) ); ?></div></div></section>
	<section class="services-compact"><div class="container services-compact__grid"><?php foreach ( $venix_concierge_compact_services as $venix_concierge_service ) : ?><article id="<?php echo esc_attr( $venix_concierge_service['id'] ); ?>" class="services-compact__card services-compact__card--<?php echo esc_attr( $venix_concierge_service['surface'] ); ?>"><div class="services-compact__media" role="img" aria-label="Photography placeholder for <?php echo esc_attr( $venix_concierge_service['title'] ); ?>."></div><?php get_template_part( 'template-parts/components/badge/badge', null, array( 'label' => $venix_concierge_services_content['additional']['compact_badge'], 'tone' => 'brand' ) ); ?><h2><?php echo esc_html( $venix_concierge_service['title'] ); ?></h2><span class="services-rule" aria-hidden="true"></span><p><?php echo esc_html( $venix_concierge_service['copy'] ); ?></p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => $venix_concierge_service['cta'], 'url' => $venix_concierge_contact_url, 'variant' => 'text', 'size' => 'sm' ) ); ?></article><?php endforeach; ?></div></section>
	<section class="services-cta"><div class="container services-cta__content"><h2><?php echo esc_html( $venix_concierge_services_content['cta']['title'] ); ?></h2><p><?php echo esc_html( $venix_concierge_services_content['cta']['copy'] ); ?></p><?php get_template_part( 'template-parts/components/button/button', null, array( 'label' => $venix_concierge_services_content['cta']['button'], 'url' => $venix_concierge_contact_url, 'variant' => 'gold' ) ); ?></div></section>
</main>
