<?php
/** Shared production header. @package VenixConcierge */
$venix_concierge_contact_url = venix_concierge_page_url( 'contact' );
$venix_concierge_labels      = venix_concierge_shell_labels();
?>
<header class="site-header" data-site-header>
	<div class="container site-header__inner">
		<?php if ( has_custom_logo() ) : ?>
			<div class="site-header__brand"><?php the_custom_logo(); ?></div>
		<?php else : ?>
			<a class="site-header__brand" href="<?php echo esc_url( venix_concierge_page_url( 'home' ) ); ?>" aria-label="<?php esc_attr_e( 'Venix Concierge home', 'venix-concierge' ); ?>"><span>VENIX <small>CONCIERGE</small></span></a>
		<?php endif; ?>
		<button class="mobile-menu-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation-panel" data-menu-toggle><span class="screen-reader-text" data-menu-toggle-label><?php esc_html_e( 'Open menu', 'venix-concierge' ); ?></span><span aria-hidden="true" data-menu-toggle-icon></span></button>
		<div id="primary-navigation-panel" class="site-header__panel" data-navigation-panel>
			<nav class="site-navigation" aria-label="<?php esc_attr_e( 'Primary navigation', 'venix-concierge' ); ?>">
				<?php if ( has_nav_menu( 'primary' ) ) { wp_nav_menu( array( 'theme_location' => 'primary', 'container' => false, 'fallback_cb' => false ) ); } else { ?>
				<ul><li><a href="<?php echo esc_url( venix_concierge_page_url( 'home' ) ); ?>"><?php echo esc_html( $venix_concierge_labels['home'] ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'about' ) ); ?>"><?php echo esc_html( $venix_concierge_labels['about'] ); ?></a></li><li class="menu-item-has-children"><a href="<?php echo esc_url( venix_concierge_page_url( 'services' ) ); ?>"><?php echo esc_html( $venix_concierge_labels['services'] ); ?></a><ul class="sub-menu"><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'chauffeur' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Chauffeur & Private Transfers', 'Szofer i transfery prywatne' ) ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'airport' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Airport Transfers', 'Transfery lotniskowe' ) ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'events' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Business & Private Events', 'Wydarzenia biznesowe i prywatne' ) ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'delegations' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Delegations & Diplomatic', 'Delegacje i dyplomacja' ) ); ?></a></li></ul></li><li class="menu-item-has-children"><a href="<?php echo esc_url( venix_concierge_page_url( 'services' ) ); ?>"><?php echo esc_html( $venix_concierge_labels['other_services'] ); ?></a><ul class="sub-menu"><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'protection' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Private Protection', 'Ochrona osobista' ) ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'flights' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Private Flights', 'Loty prywatne' ) ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'embassy' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Embassy Services', 'Obsługa ambasad' ) ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'concierge' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Concierge Services', 'Usługi concierge' ) ); ?></a></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'services', 'weddings' ) ); ?>"><?php echo esc_html( venix_concierge_language_copy( 'Weddings', 'Śluby i wesela' ) ); ?></a></li></ul></li><li><a href="<?php echo esc_url( venix_concierge_page_url( 'fleet' ) ); ?>"><?php echo esc_html( $venix_concierge_labels['fleet'] ); ?></a></li><li><a href="<?php echo esc_url( $venix_concierge_contact_url ); ?>"><?php echo esc_html( $venix_concierge_labels['contact'] ); ?></a></li></ul>
				<?php } ?>
			</nav><div class="site-header__actions"><?php venix_concierge_render_language_switcher(); ?><a class="site-header__cta" href="<?php echo esc_url( $venix_concierge_contact_url ); ?>"><?php echo esc_html( $venix_concierge_labels['request'] ); ?></a></div>
		</div>
	</div>
</header>
